BEGIN;

ALTER TABLE LOCALIZACAO_USUARIOS
    ADD COLUMN IF NOT EXISTS CIDADE_FK INTEGER;

UPDATE LOCALIZACAO_USUARIOS AS L
SET CIDADE_FK = U.CIDADE_FK
FROM USUARIOS AS U
WHERE U.ID_USUARIO = L.USUARIO_FK
  AND L.CIDADE_FK IS NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM LOCALIZACAO_USUARIOS
        WHERE CIDADE_FK IS NULL
    ) THEN
        RAISE EXCEPTION
            'Nao foi possivel preencher CIDADE_FK para todas as localizacoes existentes.';
    END IF;
END $$;

ALTER TABLE LOCALIZACAO_USUARIOS
    ALTER COLUMN CIDADE_FK SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_localizacao_cidade'
          AND conrelid = 'localizacao_usuarios'::regclass
    ) THEN
        ALTER TABLE LOCALIZACAO_USUARIOS
            ADD CONSTRAINT FK_LOCALIZACAO_CIDADE
            FOREIGN KEY (CIDADE_FK)
            REFERENCES CIDADES (ID_CIDADE);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS IX_LOCALIZACAO_USUARIOS_CIDADE_FK
    ON LOCALIZACAO_USUARIOS (CIDADE_FK);

COMMIT;
