CREATE TABLE IF NOT EXISTS ARQUIVOS_UPLOAD (
    CAMINHO_ARQUIVO VARCHAR(255) PRIMARY KEY,
    TIPO_CONTEUDO VARCHAR(100) NOT NULL,
    CONTEUDO BYTEA NOT NULL,
    DATA_CRIACAO TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
