BEGIN;

ALTER TABLE RECUPERACAO_SENHA
    ADD COLUMN IF NOT EXISTS CODIGO_HASH VARCHAR(128),
    ADD COLUMN IF NOT EXISTS TENTATIVAS INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS CODIGO_VALIDADO BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS TOKEN_RESET_HASH VARCHAR(128),
    ADD COLUMN IF NOT EXISTS TOKEN_RESET_EXPIRACAO TIMESTAMP,
    ADD COLUMN IF NOT EXISTS DATA_USO TIMESTAMP;

UPDATE RECUPERACAO_SENHA
SET USADO = TRUE
WHERE CODIGO_HASH IS NULL;

CREATE INDEX IF NOT EXISTS IX_RECUPERACAO_SENHA_USUARIO_ATIVO
    ON RECUPERACAO_SENHA (USUARIO_FK, USADO, DATA_EXPIRACAO);

CREATE UNIQUE INDEX IF NOT EXISTS UX_RECUPERACAO_SENHA_TOKEN_RESET_HASH
    ON RECUPERACAO_SENHA (TOKEN_RESET_HASH)
    WHERE TOKEN_RESET_HASH IS NOT NULL;

COMMIT;
